# Application configuration
server:  port: 8081

spring:  data:    mongodb:      database: visitors-dev
      host: localhost
      port: 27017
    web:      pageable:        default-page-size: 10
  mail:
    host: smtp.gmail.com
    username: tempaccolite@gmail.com
    password: TempAccolite@2019
    properties:
      mail:
        port: 587
        properties:
          mail:
            smtp:
              starttls:
                enable: true
                required: false
        
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 978462556205-2l4sdcobrd4htrcrdmnuokktuuca8ms1.apps.googleusercontent.com
            client-secret: <client-secret>
logging:  level:
    com.accolite.visitor: DEBUG  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %C{1.} %msg%n"

applicationURL: http://13.233.40.37:8081

# Message constants
NEW: Visit entry is created for <VisitorName>
PENDING: Status is Pending for <VisitorName>
SCHEDULED: Visit is scheduled for <VisitorName> by <ContactPerson>
APPROVED: Visit is approved for <VisitorName> by <ContactPerson>
DECLINED: Visit is declined for <VisitorName> by <ContactPerson>
CANCELLED: Visit is cancelled for <VisitorName> by <LoggedUser>
COMPLETED: <VisitorName> has completed his/her visit
FAILED: Visit is failed for <VisitorName> due to some internal issues

app:
  security:
    token:
      alias: visitor
      expireSeconds: 200000
      path: visitor.jks
      type: JKS
      password: <password>
#    cookie:
#      age: 180